### ISSUE TITLE
Plugin don't work correctly in module reset if it has nasted structure in state

### ISSUE THREAD

**Issue by Erlast** [ianwalter/vuex-reset#161]

**Comment by ianwalter** [comment]
I don't see the issue. Can you create a [codesandbox](https://codesandbox.io/) reproduction?

**Comment by Erlast** [comment]
> I don't see the issue. Can you create a [codesandbox](https://codesandbox.io/) reproduction?

https://codesandbox.io/embed/myoyqq2yvx?fontsize=14, I'm creating for the first time the issue , that's why I can mistaken

**Comment by ianwalter** [comment]
I couldn't get your reproduction working really, but I think I know what the problem is and a fix will be in soon. Thanks.

**Comment by ianwalter** [comment]
Thanks again, fixed in v2.1.1.

**Comment by Erlast** [comment]
Thanks a lot

**Comment by xerosanyam** [comment]
Facing same problem with latest version :-/

**Comment by ianwalter** [comment]
@xerosanyam Do you still have an issue if you use version 4.2.1?
