### ISSUE TITLE
Fixing #161 Bug

### ISSUE THREAD

**Issue by spyke113** [ianwalter/vuex-reset#163]
After fixing #161 there is the following problem:
Reset whole state works great.
Reset module state with objects works great.
But after reset module state with objects, reset whole state doesn't work correctly, namely, all modules are reset except that it was reset in the previous step.

It seems to me that instead:
```js
store.replaceState({ ...clone(state), [mod]: initialState[mod] });
```
it will be more correct to write so
```js
store.replaceState({ ...clone(state), [mod]: clone(initialState[mod]) });
```

P.S. clones will enslave the world... =))

**Comment by ianwalter** [comment]
Fixed in v2.1.2, thanks!
