### ISSUE TITLE
not compatible with typescript

### ISSUE THREAD

**Issue by xerosanyam** [ianwalter/vuex-reset#298]
When importing like:
`import VuexReset from '@ianwalter/vuex-reset'`
getting warning:
`Could not find a declaration file for module '@ianwalter/vuex-reset'.`

When importing by:
`const VuexReset = require('@ianwalter/vuex-reset')`
Getting Error:
`VuexReset is not a function`

Please suggest how to solve this.
Thanks

**Comment by spaasis** [comment]
This project doesn't seem to have any typings, and that's what the error is about. The error message (in vscode at least) provides the solution:

Create a `d.ts`-file (for example vuex-reset.d.ts) to the project root that has the following contents:
`declare module '@ianwalter/vuex-reset';`

**Comment by ianwalter** [comment]
I would accept a PR for TypeScript typings but I won't be adding it myself.

**Comment by xerosanyam** [comment]
Thanks for the feeback guys. I was starting my typescript journey & this was a blocker back then. Now I understand better how things work in typescript world. 😄
