### ISSUE TITLE
Resetting state to undefined

### ISSUE THREAD

**Issue by douglas-fabiano** [ianwalter/vuex-reset#322]
Using the store.registerModule () method after the vuex instance is created. When mutation reset () is called the undefined value is assigned to the state.

Before calling reset () mutation
![image](https://user-images.githubusercontent.com/39135298/72443413-9a2be480-3784-11ea-9676-f4c70ae28e58.png)

After
![image](https://user-images.githubusercontent.com/39135298/72443526-c6476580-3784-11ea-8457-bb271016d0ce.png)

**Comment by ianwalter** [comment]
@douglas-fabiano Can you use `store.registerModuleState` instead? Sorry it's not documented. It has the same API as `registerModule`. See the code at https://github.com/ianwalter/vuex-reset/blob/master/index.js#L46

**Comment by douglas-fabiano** [comment]
@ianwalter Using the `store.registerModuleState` method worked perfectly. Thank you!!!
